name: update-gitcode
on:

  workflow_dispatch: 

  push:
    branches:
      - main

#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

jobs:
  sync-main:
    # if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - id: setup-ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GITCODE_SSH_KEY }}
      - id: add-know-hosts
        run: |
          ssh-keyscan gitcode.com >> ~/.ssh/known_hosts
#       - id: checkout
#         uses: actions/checkout@v6
#         with:
#           repository: git@gitcode.com:flagos-ai/testsync.git
#           ref: main
#           ssh-user: weixin_39841130
#           ssh-strict: true
#           persist-credentials: true
#           clean: true
#           set-safe-directory: true
      - id: checkout
        run: |
          git clone git@gitcode.com:flagos-ai/testsync.git testsync

      - id: rebase
        run: |
          cd testsync
          git checkout main
          echo "adding new remote to github"
          git remote add github https://github.com/flagos-ai/test-sync.git
          echo "fetching github branches"
          git fetch github
          git status
          echo "git rebase"
          git rebase github/main
          echo "git push"
          git config global user.name weixin_39841130
          git config global user.email weixin_39841130@noreply.gitcode.com
          git push -u origin main -f
